# BLS Data Download — bulk flat files

In [1]:
import logging
import sys
from datetime import date

logging.basicConfig(level=logging.INFO, stream=sys.stderr)

start_date = date(2024, 4, 1)
end_date = date(2024, 6, 1)

## QCEW (no API key required)

In [2]:
from bls_stats.download.qcew import download_qcew

qcew_df = download_qcew(start_date, end_date)
print(f"QCEW: {len(qcew_df)} rows")
qcew_df.head()

INFO:bls_stats.download.qcew:QCEW: downloading bulk data for 2024
INFO:bls_stats.download.fetch:Downloading https://data.bls.gov/cew/data/files/2024/csv/2024_qtrly_singlefile.zip
INFO:httpx:HTTP Request: GET https://data.bls.gov/cew/data/files/2024/csv/2024_qtrly_singlefile.zip "HTTP/1.1 200 OK"
INFO:bls_stats.download.fetch:Zip contains 1 CSV files
INFO:bls_stats.download.qcew:QCEW: 14659636 rows for year 2024
INFO:bls_stats.download.qcew:QCEW: wrote 3664909 rows to data/qcew/qcew_estimates.parquet

QCEW: 3664909 rows

shape: (5, 43)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ area_fips ┆ own_code ┆ industry_ ┆ agglvl_co ┆ … ┆ oty_qtrly ┆ oty_avg_w ┆ oty_avg_w ┆ downloade │
│ ---       ┆ ---      ┆ code      ┆ de        ┆   ┆ _contribu ┆ kly_wage_ ┆ kly_wage_ ┆ d         │
│ str       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ tions_pct ┆ chg       ┆ pct_chg   ┆ ---       │
│           ┆          ┆ str       ┆ i64       ┆   ┆ _ch…      ┆ ---       ┆ ---       ┆ datetime[ │
│           ┆          ┆           ┆           ┆   ┆ ---       ┆ i64       ┆ f64       ┆ μs]       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 01000     ┆ 0        ┆ 10        ┆ 50        ┆ … ┆ -24.9     ┆ 43        ┆ 3.9       ┆ 2026-04-1 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2 17:23:2 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.714463  │
│ 01000     ┆ 1        ┆ 10        ┆ 51        ┆ … ┆ 0.0       ┆ 43        ┆ 2.3       ┆ 2026-04-1 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2 17:23:2 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.714463  │
│ 01000     ┆ 1        ┆ 101       ┆ 52        ┆ … ┆ 0.0       ┆ 0         ┆ 0.0       ┆ 2026-04-1 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2 17:23:2 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.714463  │
│ 01000     ┆ 1        ┆ 1013      ┆ 53        ┆ … ┆ 0.0       ┆ 0         ┆ 0.0       ┆ 2026-04-1 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2 17:23:2 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.714463  │
│ 01000     ┆ 1        ┆ 102       ┆ 52        ┆ … ┆ 0.0       ┆ 43        ┆ 2.3       ┆ 2026-04-1 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2 17:23:2 │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1.714463  │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### BED

In [3]:
from bls_stats.download.bed import download_bed

bed_df = download_bed(start_date, end_date)
print(f"BED: {len(bed_df)} rows")
bed_df.head()

INFO:bls_stats.download.bed:BED: downloading flat file
INFO:bls_stats.download.fetch:Downloading https://download.bls.gov/pub/time.series/bd/bd.data.0.Current
INFO:httpx:HTTP Request: GET https://download.bls.gov/pub/time.series/bd/bd.data.0.Current "HTTP/1.1 200 OK"
INFO:bls_stats.download.bed:BED: 3515328 total rows downloaded
INFO:bls_stats.download.bed:BED: wrote 34464 rows to data/bed/bed_estimates.parquet

BED: 34464 rows

shape: (5, 21)
┌──────────────┬──────┬────────┬───────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ series_id    ┆ year ┆ period ┆ value ┆ … ┆ seasonally_ ┆ geographic_ ┆ geographic_ ┆ downloaded  │
│ ---          ┆ ---  ┆ ---    ┆ ---   ┆   ┆ adjusted    ┆ type        ┆ code        ┆ ---         │
│ str          ┆ i32  ┆ str    ┆ str   ┆   ┆ ---         ┆ ---         ┆ ---         ┆ datetime[μs │
│              ┆      ┆        ┆       ┆   ┆ bool        ┆ str         ┆ str         ┆ ]           │
╞══════════════╪══════╪════════╪═══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ BDS000000000 ┆ 2024 ┆ Q02    ┆ 7639  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000011000 ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:23:22.97 │
│ 1LQ5         ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 9037        │
│ BDS000000000 ┆ 2024 ┆ Q02    ┆ 5.8   ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000011000 ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:23:22.97 │
│ 1RQ5         ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 9037        │
│ BDS000000000 ┆ 2024 ┆ Q02    ┆ 6078  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000011000 ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:23:22.97 │
│ 2LQ5         ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 9037        │
│ BDS000000000 ┆ 2024 ┆ Q02    ┆ 4.6   ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000011000 ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:23:22.97 │
│ 2RQ5         ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 9037        │
│ BDS000000000 ┆ 2024 ┆ Q02    ┆ 1561  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000011000 ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:23:22.97 │
│ 3LQ5         ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 9037        │
└──────────────┴──────┴────────┴───────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### CES

In [4]:
from bls_stats.download.ces import download_ces

ces_df = download_ces(start_date, end_date)
print(f"CES: {len(ces_df)} rows")
ces_df.head()

INFO:bls_stats.download.ces:CES: downloading flat file
INFO:bls_stats.download.fetch:Downloading https://download.bls.gov/pub/time.series/ce/ce.data.0.AllCESSeries
INFO:httpx:HTTP Request: GET https://download.bls.gov/pub/time.series/ce/ce.data.0.AllCESSeries "HTTP/1.1 200 OK"
INFO:bls_stats.download.ces:CES: 8249737 total rows downloaded
INFO:bls_stats.download.ces:CES: wrote 66125 rows to data/ces/ces_estimates.parquet

CES: 66125 rows

shape: (5, 16)
┌─────────────┬──────┬────────┬────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ series_id   ┆ year ┆ period ┆ value  ┆ … ┆ seasonally_ ┆ geographic_ ┆ geographic_ ┆ downloaded  │
│ ---         ┆ ---  ┆ ---    ┆ ---    ┆   ┆ adjusted    ┆ type        ┆ code        ┆ ---         │
│ str         ┆ i32  ┆ str    ┆ str    ┆   ┆ ---         ┆ ---         ┆ ---         ┆ datetime[μs │
│             ┆      ┆        ┆        ┆   ┆ bool        ┆ str         ┆ str         ┆ ]           │
╞═════════════╪══════╪════════╪════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ CES00000000 ┆ 2024 ┆ M04    ┆ 157530 ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 01          ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 17:24:17.04 │
│             ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 9067        │
│ CES00000000 ┆ 2024 ┆ M05    ┆ 157608 ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 01          ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 17:24:17.04 │
│             ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 9067        │
│ CES00000000 ┆ 2024 ┆ M06    ┆ 157695 ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 01          ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 17:24:17.04 │
│             ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 9067        │
│ CES00000000 ┆ 2024 ┆ M04    ┆ 78635  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 10          ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 17:24:17.04 │
│             ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 9067        │
│ CES00000000 ┆ 2024 ┆ M05    ┆ 78670  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 10          ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 17:24:17.04 │
│             ┆      ┆        ┆        ┆   ┆             ┆             ┆             ┆ 9067        │
└─────────────┴──────┴────────┴────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### SAE

In [5]:
from bls_stats.download.sae import download_sae

sae_df = download_sae(start_date, end_date)
print(f"SAE: {len(sae_df)} rows")
sae_df.head()

INFO:bls_stats.download.sae:SAE: downloading flat file
INFO:bls_stats.download.fetch:Downloading https://download.bls.gov/pub/time.series/sm/sm.data.0.Current
INFO:httpx:HTTP Request: GET https://download.bls.gov/pub/time.series/sm/sm.data.0.Current "HTTP/1.1 200 OK"
INFO:bls_stats.download.sae:SAE: 5875838 total rows downloaded
INFO:bls_stats.download.sae:SAE: wrote 68781 rows to data/sae/sae_estimates.parquet

SAE: 68781 rows

shape: (5, 18)
┌──────────────┬──────┬────────┬───────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ series_id    ┆ year ┆ period ┆ value ┆ … ┆ seasonally_ ┆ geographic_ ┆ geographic_ ┆ downloaded  │
│ ---          ┆ ---  ┆ ---    ┆ ---   ┆   ┆ adjusted    ┆ type        ┆ code        ┆ ---         │
│ str          ┆ i32  ┆ str    ┆ str   ┆   ┆ ---         ┆ ---         ┆ ---         ┆ datetime[μs │
│              ┆      ┆        ┆       ┆   ┆ bool        ┆ str         ┆ str         ┆ ]           │
╞══════════════╪══════╪════════╪═══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ SMS000000000 ┆ 2024 ┆ M04    ┆ 35.3  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 00000021     ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.70 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 0721        │
│ SMS000000000 ┆ 2024 ┆ M05    ┆ 82.4  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 00000021     ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.70 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 0721        │
│ SMS000000000 ┆ 2024 ┆ M06    ┆ 66.7  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 00000021     ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.70 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 0721        │
│ SMS000000000 ┆ 2024 ┆ M04    ┆ 86.3  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 00000022     ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.70 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 0721        │
│ SMS000000000 ┆ 2024 ┆ M05    ┆ 84.3  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 00000022     ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.70 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 0721        │
└──────────────┴──────┴────────┴───────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

### JOLTS

In [6]:
from bls_stats.download.jolts import download_jolts

jolts_df = download_jolts(start_date, end_date)
print(f"JOLTS: {len(jolts_df)} rows")
jolts_df.head()

INFO:bls_stats.download.jolts:JOLTS: downloading flat file
INFO:bls_stats.download.fetch:Downloading https://download.bls.gov/pub/time.series/jt/jt.data.0.Current
INFO:httpx:HTTP Request: GET https://download.bls.gov/pub/time.series/jt/jt.data.0.Current "HTTP/1.1 200 OK"
INFO:bls_stats.download.jolts:JOLTS: 372224 total rows downloaded
INFO:bls_stats.download.jolts:JOLTS: wrote 5958 rows to data/jolts/jolts_estimates.parquet

JOLTS: 5958 rows

shape: (5, 19)
┌──────────────┬──────┬────────┬───────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ series_id    ┆ year ┆ period ┆ value ┆ … ┆ seasonally_ ┆ geographic_ ┆ geographic_ ┆ downloaded  │
│ ---          ┆ ---  ┆ ---    ┆ ---   ┆   ┆ adjusted    ┆ type        ┆ code        ┆ ---         │
│ str          ┆ i32  ┆ str    ┆ str   ┆   ┆ ---         ┆ ---         ┆ ---         ┆ datetime[μs │
│              ┆      ┆        ┆       ┆   ┆ bool        ┆ str         ┆ str         ┆ ]           │
╞══════════════╪══════╪════════╪═══════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ JTS000000000 ┆ 2024 ┆ M04    ┆ 5469  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000HIL    ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.91 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 3824        │
│ JTS000000000 ┆ 2024 ┆ M05    ┆ 5492  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000HIL    ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.91 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 3824        │
│ JTS000000000 ┆ 2024 ┆ M06    ┆ 5137  ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000HIL    ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.91 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 3824        │
│ JTS000000000 ┆ 2024 ┆ M04    ┆ 3.5   ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000HIR    ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.91 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 3824        │
│ JTS000000000 ┆ 2024 ┆ M05    ┆ 3.5   ┆ … ┆ true        ┆ national    ┆ US          ┆ 2026-04-12  │
│ 000000HIR    ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 17:24:18.91 │
│              ┆      ┆        ┆       ┆   ┆             ┆             ┆             ┆ 3824        │
└──────────────┴──────┴────────┴───────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

## Summary

In [7]:
import polars as pl

summary = pl.DataFrame({
    "program": ["QCEW", "BED", "CES", "SAE", "JOLTS"],
    "rows": [len(qcew_df), len(bed_df), len(ces_df), len(sae_df), len(jolts_df)],
})
summary

shape: (5, 2)
┌─────────┬─────────┐
│ program ┆ rows    │
│ ---     ┆ ---     │
│ str     ┆ i64     │
╞═════════╪═════════╡
│ QCEW    ┆ 3664909 │
│ BED     ┆ 34464   │
│ CES     ┆ 66125   │
│ SAE     ┆ 68781   │
│ JOLTS   ┆ 5958    │
└─────────┴─────────┘